spring:
  datasource:
    username: root
    password: "@ditShh0828"
    url: jdbc:mysql://localhost:3306/moviesflixdb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: "ak2057338@gmail.com"
    password: "nyht jesq znhi uycd"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

project:
  poster: posters/

base:
  url: "http://localhost:8080"

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG